### ISSUE TITLE
Speak Test

### ISSUE THREAD

**Issue by dkman94** [fastrapp/fastr-ios-app#5]
Preliminary tasks:
1) Create a "slurred speech" model using Teachable Machine
2) Convert model to TFLite format and deploy to the device

User tasks:
1) Repeat the following sentence: "Today is a sunny day", "The spy fled to Greece", "In the winter the president lives in washington"
2) Using the model classify the recorded speech as "slurred" or not

Page UI:
-Display required user action as a prompt at the bottom of the page
-Display some sort of loading/listening item in the center of the page 

Resources: https://blog.tensorflow.org/2020/12/build-sound-classification-models-for-mobile-apps-with-teachable-machine-and-tflite.html
https://www.tensorflow.org/lite/guide/ios

Another option (since teachable machine limits to 1 sec sample) - https://www.tensorflow.org/lite/tutorials/model_maker_audio_classification

From Sam:
Speech: Go through the language exam. Check patient's comprehnesion, name simple and rare objects, repetition of sentences, reading, and writing (they can type). Also test for issues with expressing language (dysarthria) with the "ga ga ga" "la la la" and "ba ba ba" sounds.

**Comment by JT17** [comment]
Done for now
